### PR TITLE
Add no-same-owner flag to tar.

### PR DESCRIPTION
**Pull request by stikonas**

### CODE REVIEW

**Comment by stikonas** [comment]
Ok, thanks I think that should be enough to build it in live-bootstrap.

**Comment by stikonas** [comment]
Maybe worth tagging this?

**Comment by schierlm** [comment]
Once you confirmed it working (you can tag it on your own fork for testing), sure.

Do you prefer tags that include the version of autogen bootstrapped (like I did with guile) or just neutral tags like v1.0?

**Comment by stikonas** [comment]
Well, I just tried it with commit archives and it went as far as gnulib import which I still need to arrange. But I think at that stage things are not problematic anymore.

I'm find with any versioning scheme for tags. Though maybe v1.0 is easier to update if we need to add more scripting fixes (e.g. debian static stuff).

**Comment by schierlm** [comment]
https://github.com/schierlm/gnu-autogen-bootstrapping/releases/tag/autogen-5.18.16-v1.0

**Comment by stikonas** [comment]
argh, there is probably another live-bootstrap issue, though I'm not sure what causes it (maybe again bubblewrap).

```
bootstrap complete
./bootstrap_tarball.sh: line 171: ./configure: Permission denied
```
And I can indeed see that configure has no execute permission.

**Comment by schierlm** [comment]
I'm sure you will figure this out. Then you can decide whether to patch locally or submit a PR :)

**Comment by stikonas** [comment]
well, `chmod +x configure` would fix it but I'll see if I can workaround it in live-bootstrap.

**Comment by stikonas** [comment]
Ok, I'll have to fix it in live-bootstrap, it has way more problems then just configure but I think I traced it to broken `sed` (it removes executable bit).

**Comment by stikonas** [comment]
Ok, everything is solved by upgrading `sed`, so no further changes are needed here.

We still had original `sed` build without autotools (used manual makefile) that had not defined `HAVE_FCHOWN`, so sed could not restore permissions after in place editing.

**Pull request merged**
